# See https://pre-commit.com for more information
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
    - id: trailing-whitespace
    - id: check-yaml
    - id: check-added-large-files
    - id: check-ast
    - id: check-executables-have-shebangs
    - id: check-merge-conflict
    - id: forbid-submodules
    - id: mixed-line-ending
    - id: requirements-txt-fixer

- repo: https://github.com/pre-commit/mirrors-autopep8
  rev: v2.0.4
  hooks:
    - id: autopep8

- repo: https://github.com/asottile/dead
  rev: v1.5.2
  hooks:
    - id: dead
