# See https://pre-commit.com for more information
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
    - id: trailing-whitespace
    - id: check-yaml
    - id: check-added-large-files
    - id: check-executables-have-shebangs
    - id: check-merge-conflict
    - id: forbid-submodules
    - id: mixed-line-ending
    - id: end-of-file-fixer

- repo: https://github.com/adrienverge/yamllint
  rev: v1.32.0
  hooks:
    - id: yamllint
      files: resume.yaml
